title: Trees, the planet
author: Charles D. Minsavage-Davis
email: charlesdavisenvi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright © 2022 by C.D. Minsavage-Davis
  All rights reserved. No part of the work on this site may be reproduced or used in any manner without written consent of the copyright owner except for quotations in review.

# social links
twitter_username: cdmdPhD # DO NOT include the @ character, or else the build will fail!
github_username:  CDMDPhD # DO NOT include the @ character, or else the build will fail!
orcid:  0000-0001-6775-9810  

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
